[package]
name = "qubit-mime"
version = "0.10.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-mime"
description = "MIME type detection utilities for Rust based on filename glob rules and content magic"
homepage = "https://github.com/qubit-ltd/rs-mime"
documentation = "https://docs.rs/qubit-mime"
readme = "README.md"
keywords = ["mime", "detection", "media-type", "file", "qubit"]
categories = ["filesystem", "parser-implementations"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_mime"
doctest = true

[dependencies]
regex = "1.12"
roxmltree = "0.21"
thiserror = "2.0"

qubit-io = { path = "../rs-io", version = "0.14" }
qubit-fs = { path = "../rs-fs", version = "0.2" }
qubit-codec-misc = { path = "../rs-codec-misc", version = "0.3" }
qubit-command = { version = "0.6", path = "../rs-command" }
qubit-config = { path = "../rs-config", version = "0.14" }
qubit-datatype = { version = "0.9", default-features = false, features = ["converter"] }
qubit-local-files = { path = "../rs-local-files", version = "0.7" }
qubit-spi = { path = "../rs-spi", version = "0.11" }

[dev-dependencies]
qubit-fs-local = { path = "../rs-fs-local", version = "0.1" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
